// Generated by CoffeeScript 1.4.0
var animation, delayThenCall;

delayThenCall = function(millisecs) {
  var d;
  d = Q.defer();
  setTimeout(function() {
    return d.resolve();
  }, millisecs);
  return d.promise;
};

animation = function() {
  return delayThenCall(2000).then(function() {
    $("#subheader").html("is noise");
    return delayThenCall(2000);
  }).then(function() {
    $("#subheader").html("is open");
    return delayThenCall(2000);
  }).then(function() {
    $("#subheader").html("is hacktive");
    return delayThenCall(2000);
  }).then(function() {
    return $("#subheader").html("is a nebulous collective of people from different backgrounds working together on what feels right");
  });
};

$(function() {
  return animation().then(animation).then(animation);
});
